In [1]:
import psycopg2
import config as creds
import sqlalchemy
from sqlalchemy import create_engine
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
from datetime import datetime
from scipy import stats
import matplotlib.pyplot as plt
plt.style.use('dark_background')
import seaborn as sns

from bokeh.models import *
from bokeh.plotting import *
from bokeh.io import *
from bokeh.tile_providers import *
from bokeh.palettes import *
from bokeh.transform import *
from bokeh.layouts import *

BokehDeprecationWarning: CARTODBPOSITRON was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.CARTODBPOSITRON) instead.
BokehDeprecationWarning: CARTODBPOSITRON_RETINA was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.CARTODBPOSITRON_RETINA) instead.
BokehDeprecationWarning: STAMEN_TERRAIN was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.STAMEN_TERRAIN) instead.
BokehDeprecationWarning: STAMEN_TERRAIN_RETINA was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.STAMEN_TERRAIN_RETINA) instead.
BokehDeprecationWarning: STAMEN_TONER was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.STAMEN_TONER) instead.
BokehDeprecationWarning: STAMEN_TONER_BACKGROUND was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.STAMEN_TONER_BACKGROUND) instead.
BokehDeprecationWarning: STAMEN_TONER_LABELS was deprecated in Bokeh 1.1.0 and will be removed, use get_provider(Vendors.STAMEN_TONER_LABELS) instead.

In [2]:
user=creds.PGUSER
password=creds.PGPASSWORD
host=creds.PGHOST
port=5432
database=creds.PGDATABASE

In [3]:
engine_str=f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(engine_str)
conn = engine.raw_connection()
print('Connected')
cur = conn.cursor()
print('Cursor created')

Connected
Cursor created

In [4]:
query1='''
SELECT *
FROM raw_energy_data r
'''

In [5]:
df1=pd.read_sql(query1,conn)

In [6]:
conn.close()
print('closed')

closed

In [7]:
df1 = pd.melt(df1, id_vars=['latitude','longitude','pid', 'dcrealpropertyid','ward','postalcode','yearbuilt','reportingyear','reportstatus','primarypropertytype_selfselect','taxrecordfloorarea','reportedbuildinggrossfloorarea','energystarscore'], 
            value_vars=['naturalgas_kbtu_january', 'naturalgas_kbtu_february','naturalgas_kbtu_march', 'naturalgas_kbtu_april', 'naturalgas_kbtu_may','naturalgas_kbtu_june', 'naturalgas_kbtu_july','naturalgas_kbtu_august', 'naturalgas_kbtu_september',
       'naturalgas_kbtu_october', 'naturalgas_kbtu_november','naturalgas_kbtu_december', 'electricityuse_kbtu_january', 'electricityuse_kbtu_february', 'electricityuse_kbtu_march',
        'electricityuse_kbtu_april', 'electricityuse_kbtu_may','electricityuse_kbtu_june', 'electricityuse_kbtu_july',
        'electricityuse_kbtu_august', 'electricityuse_kbtu_september', 'electricityuse_kbtu_october', 'electricityuse_kbtu_november',
       'electricityuse_kbtu_december'], var_name='month', value_name='kbtu', col_level=None)

In [8]:
df1['elegas']= df1['month'].str[0]

In [9]:
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_january', 1, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_february', 2, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_march', 3, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_april', 4, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_may', 5, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_june', 6, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_july', 7, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_august', 8, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_september', 9, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_october', 10, df1['month'])
df1['month'] = np.where(df1['month'] == 'naturalgas_kbtu_november', 11, df1['month'])
df1['month']= np.where(df1['month'] == 'naturalgas_kbtu_december', 12, df1['month'])

df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_january', 1, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_febuary', 2, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_march', 3, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_april', 4, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_may', 5, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_june', 6, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_july', 7, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_august', 8, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_september', 9, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_october', 10, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_november', 11, df1['month'])
df1['month'] = np.where(df1['month'] == 'electricityuse_kbtu_december', 12, df1['month'])

In [10]:
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Adult Education','2', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Bank Branch','1', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Bank/Financial Institution','1', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'College/University','2', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'College/University (Campus-Level)','2', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Courthouse','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Data Center','16', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Distribution Center','19', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Drinking Water Treatment & Distribution','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Enclosed Mall','15', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Financial Office','10', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Fire Station','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Fitness Center/Health Club/Gym','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Food Sales','5', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Food Service','5', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Hospital (General Medical & Surgical)','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Hospital (General Medical and Surgical)','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Hotel','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'K-12 School','2', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Laboratory','17', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Library','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Manufacturing/Industrial Plant','8', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Medical Office','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Mixed Use Property','9', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Movie Theater','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Multifamily Housing','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Museum','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Non-Refrigerated Warehouse','19', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Office','10', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other','11', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Education','2', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Entertainment/Public Assembly','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Lodging/Residential','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Mall','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Public Services','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Recreation','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Restaurant/Bar','11', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Services','16', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Specialty Hospital','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other - Utility','18', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other -Utility','18', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Other/Specialty Hospital','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Outpatient Rehabilitation/Physical Therapy','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Parking','12', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Performing Arts','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Police Station','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Pre-school/Daycare','2', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Prison/Incarceration','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Recreation','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Refrigerated Warehouse','19', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Repair Services (Vehicle, Shoe, Locksmith, etc)','16', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Repair Services (Vehicle, Shoe, Locksmith, etc.)','16', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Residence Hall/Dormitory','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Residential Care Facility','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Restaurant','5', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Retail','15', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Retail Store','15', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Self-Storage Facility','19', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Senior Care Community','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Service (Vehicle Repair/Service, Postal Service)','16', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Single Family Home','7', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Social/Meeting Hall','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Stadium (Open)','3', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Strip Mall','15', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Supermarket/Grocery Store','4', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Urgent Care/Clinic/Other Outpatient','6', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Warehouse (Unrefrigerated)','19', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Wastewater Treatment Plant','13', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Wholesale Club/Supercenter','5', df1['primarypropertytype_selfselect'])
df1['primarypropertytype_selfselect'] = np.where(df1['primarypropertytype_selfselect'] == 'Worship Facility','14', df1['primarypropertytype_selfselect'])

In [11]:
df1.head()

,latitude,longitude,pid,dcrealpropertyid,ward,postalcode,yearbuilt,reportingyear,reportstatus,primarypropertytype_selfselect,taxrecordfloorarea,reportedbuildinggrossfloorarea,energystarscore,month,kbtu,elegas
0,38.905957198162,-77.0457881519479,PM2969314,0099_0050,2.0,20036,1969.0,2017,In Compliance,10,293459.0,193095.0,64.0,1,0.0,n
1,38.9040517965336,-77.0392266550262,PM1431050,0162_0821,2.0,20036,1963.0,2017,In Compliance,10,165374.0,109926.0,93.0,1,0.0,n
2,38.8760568955167,-77.0180607265186,PM2791015,0502_0184,6.0,20024,1964.0,2017,In Compliance,7,315832.0,315832.0,24.0,1,0.0,n
3,38.9029336653495,-77.0305229317398,PM3435335,0248_0830,2.0,20005,1990.0,2017,In Compliance,10,81989.0,643325.0,67.0,1,0.0,n
4,38.9021834386306,-77.0322819721985,PM1071004,0218_0079,2.0,20005,1982.0,2017,In Compliance,10,292090.0,212651.0,93.0,1,0.0,n

In [12]:
df1.to_sql('coord_table', engine)